def start():
    print("10 Chocolate Cupcakes")
    print()
    print("120g plain flour")
    print("140g sugar")
    print("1 teaspoon baking powder")
    print("40g unsalted butter")
    print("50g dark chocolate")
    print("1 free-range egg")
    print("125ml milk")
    print("1 orange juice only")
    print()
    print()
    print("1 Lemon Drizzle Cake")
    print("4 1/2 free range eggs")
    print("300g sugar")
    print("140ml double cream")
    print("3 lemons, zest only")
    print("1 pinch salt")
    print("80g unsalted butter")
    print("240g plain flour")
    print("1/2 teaspoon baking powder")

start()
